// Code generated by "stringer -type clauseKind -linecomment"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_fromClause-1]
	_ = x[_limitClause-2]
	_ = x[_offsetClause-3]
	_ = x[_orderClause-4]
	_ = x[_unionClause-5]
	_ = x[_valuesClause-6]
	_ = x[_whereClause-7]
	_ = x[_returningClause-8]
	_ = x[_setClause-9]
	_ = x[_joinClause-10]
}

const _clauseKind_name = "FROMLIMITOFFSETORDER BYUNIONVALUESWHERERETURNINGSETJOIN"

var _clauseKind_index = [...]uint8{0, 4, 9, 15, 23, 28, 34, 39, 48, 51, 55}

func (i clauseKind) String() string {
	i -= 1
	if i >= clauseKind(len(_clauseKind_index)-1) {
		return "clauseKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _clauseKind_name[_clauseKind_index[i]:_clauseKind_index[i+1]]
}
