// Code generated by "stringer -type statement -linecomment"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[deleteStmt-1]
	_ = x[insertStmt-2]
	_ = x[selectStmt-3]
	_ = x[updateStmt-4]
	_ = x[selectDistinctStmt-5]
	_ = x[selectDistinctOnStmt-6]
}

const _statement_name = "DELETEINSERTSELECTUPDATESELECT DISTINCTSELECT DISTINCT ON"

var _statement_index = [...]uint8{0, 6, 12, 18, 24, 39, 57}

func (i statement) String() string {
	i -= 1
	if i >= statement(len(_statement_index)-1) {
		return "statement(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _statement_name[_statement_index[i]:_statement_index[i+1]]
}
